### ISSUE TITLE
The SCSS contents are returned instead of the compiled CSS

### ISSUE THREAD

**Issue by sheepwall** [SymfonyCasts/sass-bundle#43] opened 2023-12-10 21:48 UTC
Hello,

I am trying to migrate from encore, and need to support some previous Bootstrap SASS modifications, so I found this library.

**Problem:**

* The CSS file served to the browser contains the original SCSS-content instead of the compiled CSS. The filetype _is_ `.css` though.
![image](https://github.com/SymfonyCasts/sass-bundle/assets/22132993/e045dfbe-8f0a-4001-9698-cfcf00a4d8f0)

**Troubleshooting:**

* `bin/console sass:build` _does_ output compiled CSS to `var/sass/admin.output.css`
* `var/dart-sass/sass assets/styles/admin.scss` returns compiled CSS
* running `bin/console sass:build` and then `asset-map:compile` works, the browser gets loadable CSS
* there are no error messages produced by `bin/console sass:build -v`

The missing step is that which I underlined from the documentation below: 

![image](https://github.com/SymfonyCasts/sass-bundle/assets/22132993/3cf31a1f-fa2e-4f26-9e1b-a58d5560623e)

**My environment, relevant code snippets:**

1) I am running the app in Docker to reflect my prod environment. Caddy in front of PHP-FPM Symfony. In development I bind-mount everything in the project folder into the Symfony container. (NOTE: I have also run `bin/console sass:build` from within the container; it produces the files, but the browser still receives SCSS content that it can't parse.)

2) Since `admin.scss` is not the default filename, I have configured it like:

```
# config/asset_mapper.yaml
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
symfonycasts_sass:
  root_sass:
    - 'assets/styles/app.scss'
    - 'assets/styles/admin.scss'
```

3) In my twig template, I "import" the SCSS file directly.

```
{# admin.html.twig #}
...
  {% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('styles/admin.scss') }}">
  {% endblock %}
...
```

4)  The contents of the `assets/styles/admin.scss` files start with
```
/* assets/styles/admin.scss
@import "./helper/_variables";
@import "../../vendor/twbs/bootstrap/scss/bootstrap";
@import "./components/gedmo-history";

$navbarwidth: 13rem;
$sidebarbutton: 40px;
$sidebartransition: 0.4s;

.text-grey-0 { color: $grey-0 !important; }

...
```

5) Output of `dart-sass` and contents of `var/sass/admin.output.css` correctly inserted the imports shown above

** My thoughts **

So the missing step (swapping the compiled CSS contents upon request) seems to be where something is going wrong (?). But looking in this repo, I am not sure how that mechanism works. If someone could point me in the right direction that would be great.

Thanks

**Comment by sheepwall** [comment] 2023-12-11 21:04
Tried looking some more at where this swap mechanism happens, but can't find it.

I tried downloading the LAST Stack symfonycasts code and installed this package and got it working quickly.

I also tried running my application using symfony serve outside of docker. Same issue as above.

**Comment by CedsTrash** [comment] 2023-12-30 18:33
Hi, I'm facing the exact same issue. Did you find a solution? Thanks.

**Comment by nanotronic** [comment] 2024-01-15 15:13
Same here.

**Comment by nanotronic** [comment] 2024-01-16 07:49
It seems to work when i add `%kernel.project_dir%`

```
symfonycasts_sass:
  root_sass:
    - '%kernel.project_dir%/assets/styles/app.scss'
    - '%kernel.project_dir%/assets/styles/admin.scss'
```

**Comment by augsve** [comment] 2024-01-19 07:16
> Hi, I'm facing the exact same issue. Did you find a solution? Thanks.

I stopped trying, intending to revisit in the future.

**Comment by sheepwall** [comment] 2024-01-19 07:17
> Hi, I'm facing the exact same issue. Did you find a solution? Thanks.

I stopped trying, intending to revisit in the future.

**Comment by xtezza** [comment] 2024-01-25 14:12
> symfonycasts_sass

I have the same issue, testing multiple possibilities but not working for me :(

**Comment by nanotronic** [comment] 2024-01-26 15:33
> > symfonycasts_sass
> 
> I have the same issue, testing multiple possibilities but not working for me :(

Have you added `%kernel.project_dir%` to the root_sass setting?

**Comment by Siniliote** [comment] 2024-02-01 09:51
Hello, 
i have same problem, i run `bin/console asset-map:compile` and it's working for me ;)

**Comment by wryk** [comment] 2024-02-19 18:49
After tumbling on the problem I think this issue is actually a duplicate of https://github.com/SymfonyCasts/sass-bundle/issues/8.

Relative paths are not fully working because of [how the bundle check if assets are supported](https://github.com/SymfonyCasts/sass-bundle/blob/v0.5.1/src/AssetMapper/SassCssCompiler.php#L29) ([the default value is a full path](https://github.com/SymfonyCasts/sass-bundle/blob/v0.5.1/src/DependencyInjection/SymfonycastsSassExtension.php#L84)).
This is why it's working fine with a full path as suggested by @nanotronic.

**Comment by bocharsky-bw** [comment] 2024-02-20 10:46
Good catch, @wryk ! Yeah, seems related to #8 . If the docs mislead it - we need to fix it, I suppose with `%kernel.project_dir%` is the best? Any volunteer for this? But with a longer perspective, I think we we should support relative paths as well, we probably could check if the path starts with `/` or no - if it starts with `/`- I would suppose it should be full path already. If no start `/` - then it's relative to `%kernel.project_dir%` path, and we should prepend `%kernel.project_dir%` to it. Any PRs are welcome!

**Comment by bocharsky-bw** [comment] 2024-02-26 10:16
I'm closing it in favor of #64 - [v0.6.0](https://github.com/SymfonyCasts/sass-bundle/releases/tag/v0.6.0) should fix it. Feel free to reopen if the issue still persists

**Closed by bocharsky-bw** 2024-02-26 10:16 UTC
